// What scripts/train-toy.mjs saves to src/toy/trained.data.js (and the test recomputes): the trained toy
// SAE, decoder directions at a few training rounds (II-5), and a λ sweep
// (II-6). Rounded so the file stays small and stable.

import { makeTrainer, directions, matchIdeas, recovered, measure, TOY_TRAINING } from './train.js';

const r6 = v => Math.round(v * 1e6) / 1e6;
const deep = x => (Array.isArray(x) ? x.map(deep) : typeof x === 'number' ? r6(x) : x);

export const SNAPSHOT_ROUNDS = [0, 40, 150, 400, TOY_TRAINING.steps];
export const SWEEP = [0, 0.1, 0.3, 0.6, 1.0, 1.5];

export function buildTrained() {
  const t = makeTrainer();
  const snapshots = [];
  for (const target of SNAPSHOT_ROUNDS) {
    t.step(target - t.round);
    snapshots.push({ round: t.round, dirs: deep(directions(t.params)) });
  }
  const p = t.params;
  const sweep = SWEEP.map(lambda => {
    const s = makeTrainer({ lambda });
    s.step(TOY_TRAINING.steps);
    const m = measure(s.params);
    return { lambda, lit: r6(m.lit), gap: r6(m.gap), recovered: recovered(s.params) };
  });
  return {
    note: 'Generated by scripts/train-toy.mjs. Toy values only.',
    main: {
      ...TOY_TRAINING,
      recovered: recovered(p),
      params: { D: p.D, F: p.F, Wenc: deep(p.Wenc), benc: deep(p.benc), Wdec: deep(p.Wdec), bdec: deep(p.bdec) },
      ideas: matchIdeas(p).map(m => ({ id: m.id, angle: r6(m.angle) })),
      ...measureRounded(p),
    },
    snapshots,
    sweep,
  };
}

function measureRounded(p) { const m = measure(p); return { lit: r6(m.lit), gap: r6(m.gap) }; }
