// Trains the toy SAE once and saves what the Act II scenes show, so the page
// never trains on load. Deterministic: tests/toy-trained.test.mjs re-runs it
// and checks the saved file matches.
//   node scripts/train-toy.mjs   → src/toy/trained.data.js

import { writeFile } from 'node:fs/promises';
import path from 'node:path';
import { buildDirections } from '../src/toy/model.js';
import { buildTrained } from '../src/toy/trained-build.js';

const ROOT = path.resolve(path.dirname(new URL(import.meta.url).pathname), '..');
// Directions first: training depends on them.
await writeFile(path.join(ROOT, 'src/toy/dirs.data.js'), `// Generated by scripts/train-toy.mjs (buildDirections in model.js). Do not edit.\nexport default ${JSON.stringify(buildDirections())};\n`);
const data = buildTrained();
await writeFile(path.join(ROOT, 'src/toy/trained.data.js'), `// Generated by scripts/train-toy.mjs. Do not edit; rerun the script.\nexport default ${JSON.stringify(data)};\n`);
console.log(`saved src/toy/trained.data.js: ${data.main.recovered}/8 ideas recovered at λ=${data.main.lambda}; sweep ${data.sweep.map(s => `λ${s.lambda}: ${s.lit.toFixed(2)} lit, gap ${(s.gap * 100).toFixed(1)}%`).join(' · ')}`);
